version: "3.8"

services:
  dps-meter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    container_name: dps-meter
    ports:
      - "1338:1338"
    volumes:
      - ./default.config.yml:/app/config.yml
